### PR TITLE
Update to version 3.0.0

### PR DESCRIPTION
**Pull request by bodono**
This PR is to update SCS to the latest version: 3.0.0. An incomplete list of changes (breaking API changes in bold):

- **renamed the `f` field in the cone to `z` to reflect the fact that it's the 'zero' primal cone**
- added support for quadratic terms in the objective `P`
- added new box cone `bu`, `bl` and `bsize` in the cone struct
- acceleration improved stability, ~~but now disabled by default~~
- added ability to apply acceleration periodically rather than every iteration
- new documentation website (still in progress, see https://www.cvxgrp.org/scs/)
- added new adaptive scale updating, which heuristically updates the scale parameter on the fly for better convergence, with new setting `adaptive_scale`
- changed the convergence tolerance to use infinity norm by default (can be compiled with l2 norm instead as was previously)
- **split eps into eps_abs and eps_rel (before eps_abs = eps_rel = eps)**
- by default eps_abs = eps_rel = 1e-4
- **added eps_infeas (previously eps_infeas = eps) for infeasibility detection and reduce the default tolerance to 1e-7**
- tweaked the normalization (aka equilibration)
- some under the hood refactoring
- added many more tests
- added ability to set a time-limit with setting `time_limit_secs`
- ~~no longer returns 'inaccurate' solutions when hitting max_iters or time_limit, just returns failure and nans instead (_open to feedback on this change_)~~
- **indirect solvers should be compiled with the `INDIRECT` flag set, which ensures that the linear system warm start is computed**, a breaking change only in the sense that not setting that flag will break the indirect solver (with a warning)
- changed some of the default params (eg `max_iter` is now `1e5` by default)
- **removed `cg_rate` setting, the CG tolerance is heuristically controlled automatically now**
- **moved `ScsSettings stgs` out of data, pass in directly to `scs` function now**
- modified the strings that SCS returns as `status` in the `info` struct (eg, all lower case now)

Overall SCS 3.0 should be faster and more reliable, as well as more flexible now that it natively supports quadratics and the box cone.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Great news! Been wondering when all this work might pay off and be released! 🥳 

It's basically impossible to comment on such a large diff, but just browsing the new (lovely-looking!) docs, I noticed that `GPU_TRANSOSE_MAT` under [compile flags](https://www.cvxgrp.org/scs/api/compile_flags.html) is missing a "P", and that the constant for -1 of the [exit values](https://www.cvxgrp.org/scs/api/exit_flags.html) is misnamed.

**Comment by kalmarek** [comment]
Great news and congratulations @bodono !

> * no longer returns 'inaccurate' solutions when hitting max_iters or time_limit, just returns failure and nans instead

I'd be much against this change to be honest. I have some really long running (like days to weeks) large optimization problems where I want to squeeze out every drop of accuracy (here `v2.1.4` achieves `~1e-11` which i need since the certification of the result can loose up to 8 decimal places of precision). It'd be shame to loose all of that just because I overshot the `eps` to `max_iters` ratio...

Given that's a (probably) very specialized application, how about different scenario: give me the best effort solution of the problem achievable in this time budget. returning `nan`s makes this impossible.

I'd ask you to reconsider this choice!

**Comment by bodono** [comment]
Thanks @h-vetinari, I fixed those typos in the docs, let me know if you spot anymore (or have other docs feedback)! You will see a lot of TODOs on the website and I am happy for anyone to contribute to those.

**Comment by bodono** [comment]
Good point @kalmarek . The reason I dropped this is because users would sometimes have a very poor 'solution' at termination that was nowhere near they're desired tolerances and use it without checking how accurate it was. I can revert to returning the 'best solution found so far', which also has the advantage of being usable as a warm start, but this doesn't deal with the bad solution issue and I'm not sure what to do about that.

**Comment by kalmarek** [comment]
@bodono, thanks for the consideration :) I actually run my simulations in chunks about ~24h long, save the results (`primal, dual, slack`) and warmstart the next round from this.

I understand your intention, and indeed that's what return statuses are for, too bad users are not checking them ;/
(nans in the solution seem to be a different way of communicating the status). If you want to keep this, maybe the old behaviour could be enabled by an option? [Adding one true flag shouldn't be too much of a deal for interfacing, but tbh. I don't know of any other solver that would return nans instead the best-effort solution, but maybe that I don't interact with many of them ;)]

**Comment by blegat** [comment]
> The reason I dropped this is because users would sometimes have a very poor 'solution' at termination that was nowhere near their desired tolerances and use it without checking how accurate it was.

I understand the concern. For JuMP, we also have users that simply use the solution without checking the status. However, we don't give any warning as that allows JuMP to be more flexible. In a sense, if we consider that JuMP is "too low level" to prevent the user to access the "best effort solution", SCS is also "too low level". I would support keeping the old behavior and not replacing it with `NaN`s. In many cases, I'm also only interested in a good enough feasible solution and I don't mind if it's not optimal.

**Comment by bodono** [comment]
OK, I've reverted to returning something if the solver hits max iters or time limit.

**Comment by bodono** [comment]
This is basically ready to be merged. I plan to do so in a few days so if there is any more feedback please let me know asap.

**Comment by kalmarek** [comment]
:tada:

**Pull request merged**
