### PR TITLE
Added instructions for building a SCS jar file on MAC

### PR DESCRIPTION
**Pull request by bsikander**
It took me quite some time to get SCS working on MAC in my eclipse project. I would like to help others by adding the steps in the read me file of SCS.

### CODE REVIEW

**Comment by bodono** [comment]
Thanks for submitting this, and sorry that it was such trouble getting it working. Would it be better to change the Makefile to do some of this so that the user doesn't have to perform so many manual steps?

**Comment by bsikander** [comment]
If we can implement some of the steps directly inside the make file then it would be great. I do not have experience with make files but with guidance I can definitely do it. As a student, it can be a good learning experience too. What do you suggest ?

**Comment by bsikander** [comment]
So, once user runs the make command you want to directly output jar file ?

**Comment by bodono** [comment]
If possible that would be the best option.

**Comment by bsikander** [comment]
Okay. As long as the make file is not ready should we include the steps in read me file ?

**Pull request merged**
